import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'

export default function()  {

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Prisma App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.home}>
          <Link href='/student'>
         <button>Student Data</button>
         </Link>
        </section>
      </main>

     
    </div>
  )
}

